server {
  listen 80;
  root /usr/share/nginx/html;

  gzip on;
  gzip_types text/css text/javascript application/javascript application/json image/svg+xml;

  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;

  location /assets/ {
    expires 1y;
  }

 
  location = /index.html {
    expires -1;
  }
}
